default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/ambv/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203']  # This line ignores long line errors
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace